Some important NumPy functions:

np.array() – Create array

np.arange() – Range of values

np.zeros() – Array of zeros

np.ones() – Array of ones

np.eye() – Identity matrix

np.linspace() – Evenly spaced values

np.random.rand() – Random values

np.shape – Array dimensions

np.reshape() – Reshape array

np.sum() – Sum of elements

np.mean() – Mean value

np.std() – Standard deviation

np.min() – Minimum value

np.max() – Maximum value

np.argmin() – Index of minimum value

np.argmax() – Index of maximum value

np.dot() – Dot product

np.matmul() – Matrix multiplication

np.transpose() – Transpose matrix

np.sort() – Sort array

1.create a numpy arr conatining number from 1 to 20 using inbuilt function

2.Create an arr of all zeroes with 10 elements and convert it to matrix

3.create an arr containing even numbers
from 2 to 20

4.create an arr find number of dimentions , shape,size,datatype and multiply every element by 2

5.create 1d arr and find sum , mean , max,min

In [10]:
# create a numpy arr conatining number from 1 to 20 using inbuilt function
import numpy as np
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
#Create an arr of all zeroes with 10 elements and convert it to matrix
import numpy as np
arr2 = np.zeros(10)
matrix = arr2.reshape(2, 5)
print(arr2)
print("Coverting into matrix:")
print(matrix)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Coverting into matrix:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [12]:
#create an arr containing even numbers from 2 to 20
arr3 = np.arange(2, 21, 2)
print("Even number from 2 to 20")
print(arr3)

Even number from 2 to 20
[ 2  4  6  8 10 12 14 16 18 20]


In [13]:
#create an arr find number of dimentions , shape,size,datatype and multiply every element by 2
arr4 = np.array([1, 2, 3, 4, 5])
print( arr4)
print("Dimensions:", arr4.ndim)
print("Shape:", arr4.shape)
print("Size:", arr4.size)
print("Data Type:", arr4.dtype)
mul =arr4*2
print(mul)


[1 2 3 4 5]
Dimensions: 1
Shape: (5,)
Size: 5
Data Type: int64
[ 2  4  6  8 10]


In [14]:
# create 1d arr and find sum , mean , max,min
arr5 = np.array([10, 20, 30, 40, 50],)
print(arr5)
print("sum =", np.sum(arr5))
print("mean =", np.mean(arr5))
print("Max =", np.max(arr5))
print("Min =", np.min(arr5))
print("std=",np.std(arr5))

[10 20 30 40 50]
sum = 150
mean = 30.0
Max = 50
Min = 10
std= 14.142135623730951


In [15]:
import numpy as np

# Create Array
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)

# Range of Values
a = np.arange(5, 26, 5)
print("Arange:", a)

# Zeros Array
zero = np.zeros((3, 4))
print("Zeros Array:\n", zero)

# Ones Array
one = np.ones((2, 5))
print("Ones Array:\n", one)

# Identity Matrix
identity = np.eye(3)
print("Identity Matrix:\n", identity)

Array: [10 20 30 40 50]
Arange: [ 5 10 15 20 25]
Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones Array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Evenly Spaced Values
line = np.linspace(0, 100, 11)
print("Linspace:", line)

# Random Numbers
rand = np.random.rand(3, 3)
print("Random Array:\n", rand)

# Shape
print("Shape:", rand.shape)

# Reshape
arr2 = np.arange(1, 13).reshape(3, 4)
print("Reshaped Array:\n", arr2)

# Aggregation Functions
print("Sum:", np.sum(arr2))
print("Mean:", np.mean(arr2))
print("Std:", np.std(arr2))

# Min, Max and Indices
print("Min:", np.min(arr2))
print("Max:", np.max(arr2))
print("Argmin:", np.argmin(arr2))
print("Argmax:", np.argmax(arr2))

# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Dot Product:\n", np.dot(A, B))
print("Matrix Multiplication:\n", np.matmul(A, B))

# Transpose
print("Transpose of A:\n", A.T)

# Sorting
nums = np.array([12, 5, 18, 3, 9])
print("Sorted Array:", np.sort(nums))

Linspace: [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
Random Array:
 [[0.17764069 0.03870646 0.35332491]
 [0.75755502 0.27170215 0.55359661]
 [0.79853473 0.95263148 0.68771782]]
Shape: (3, 3)
Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sum: 78
Mean: 6.5
Std: 3.452052529534663
Min: 1
Max: 12
Argmin: 0
Argmax: 11
Dot Product:
 [[19 22]
 [43 50]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]
Sorted Array: [ 3  5  9 12 18]


In [17]:
# Importing NumPy
import numpy as np

# Creating Arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[2, 4, 6],
                 [8, 10, 12],
                 [14, 16, 18]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# Array with specific values
zeros = np.zeros((2, 5))
ones = np.ones((4, 2))
identity = np.eye(4)

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity Matrix:\n", identity)

1D Array: [10 20 30 40 50]
2D Array:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# Range and linspace
arange_arr = np.arange(5, 30, 3)
linspace_arr = np.linspace(0, 100, 6)

print("Arange:", arange_arr)
print("Linspace:", linspace_arr)

# Random numbers
rand_arr = np.random.rand(3, 3)
print("Random Array:\n", rand_arr)

# Random integers (OTP-like)
otp = ((np.random.rand(5) * 900000) + 100000).astype(int)
print("OTP Numbers:", otp)

Arange: [ 5  8 11 14 17 20 23 26 29]
Linspace: [  0.  20.  40.  60.  80. 100.]
Random Array:
 [[0.45501134 0.43456737 0.87251341]
 [0.20531256 0.03473116 0.54052336]
 [0.9861971  0.2132629  0.79491961]]
OTP Numbers: [139535 970746 675261 973441 133854]
